const path = require('path');
const workerDb = require(path.join(__dirname, '../db/worker.js'));

let enabled = false;
let logs = [];
const MAX_LOGS = 50;

function addLog(message) {
    const timestamp = new Date().toISOString();
    logs.unshift({ timestamp, message });
    if (logs.length > MAX_LOGS) logs.pop();
}

const personas = {
    'programming': {
        name: 'DevBot',
        templates: [
            "Does anyone have experience with Rust?",
            "What's the best way to deploy a Node.js app?",
            "I found a cool library for React state management.",
            "Python vs Go: My thoughts."
        ],
        comments: [
            "Great point!",
            "Have you considered using Docker?",
            "This is exactly what I was looking for.",
            "Interesting perspective."
        ]
    },
    'news': {
        name: 'NewsBot',
        templates: [
            "Breaking: New AI model released.",
            "Tech industry layoffs continue.",
            "SpaceX launch successful.",
            "Global markets update."
        ],
        comments: [
            "Source?",
            "This is huge news.",
            "I wonder how this will affect the market.",
            "Thanks for sharing."
        ]
    },
    'funny': {
        name: 'MemeBot',
        templates: [
            "When your code compiles on the first try.",
            "Me debugging at 3 AM.",
            "Unexpected error: Success.",
            "Why did the developer cross the road?"
        ],
        comments: [
            "LOL",
            "This made my day.",
            "Relatable.",
            "😂😂😂"
        ]
    },
    'general': {
        name: 'UserBot',
        templates: [
            "How is everyone doing today?",
            "Any movie recommendations?",
            "Just started learning to cook.",
            "What music are you listening to?"
        ],
        comments: [
            "Welcome!",
            "I agree.",
            "Nice post.",
            "Have a great day!"
        ]
    }
};

async function runTask() {
    if (!enabled) return { status: 'skipped', reason: 'disabled' };

    const communities = Object.keys(personas);
    const community = communities[Math.floor(Math.random() * communities.length)];
    const persona = personas[community];
    const actionType = Math.random();

    let result = {};

    try {
        if (actionType < 0.4) {
            // New Post
            const template = persona.templates[Math.floor(Math.random() * persona.templates.length)];
            const postId = workerDb.createPost(template, template + " (Generated by " + persona.name + ")", persona.name, community);
            result = { type: 'post', id: postId, community, content: template };
            addLog(`Created post in r/${community}: "${template}"`);
        } else if (actionType < 0.8) {
            // Comment
            const posts = workerDb.getRecentPosts(community);
            if (posts.length > 0) {
                const post = posts[Math.floor(Math.random() * posts.length)];
                const comment = persona.comments[Math.floor(Math.random() * persona.comments.length)];
                const commentId = workerDb.createComment(post.id, comment, persona.name);
                result = { type: 'comment', id: commentId, postId: post.id, content: comment };
                addLog(`Commented on post ${post.id} in r/${community}: "${comment}"`);
            } else {
                result = { status: 'skipped', reason: 'no posts found' };
            }
        } else {
            // Vote
            const posts = workerDb.getRecentPosts(community);
            if (posts.length > 0) {
                const post = posts[Math.floor(Math.random() * posts.length)];
                const voteType = Math.random() > 0.2 ? 1 : -1; // Mostly upvote
                workerDb.vote('post', post.id, voteType);
                result = { type: 'vote', id: post.id, value: voteType };
                addLog(`Voted ${voteType > 0 ? 'UP' : 'DOWN'} on post ${post.id} in r/${community}`);
            } else {
                result = { status: 'skipped', reason: 'no posts found' };
            }
        }
    } catch (e) {
        console.error('Worker task error:', e);
        addLog(`Error: ${e.message}`);
        throw e;
    }

    return result;
}

module.exports = {
    getStatus: () => ({ enabled, lastRun: logs[0]?.timestamp }),
    setEnabled: (val) => { enabled = val; addLog(`Worker ${enabled ? 'enabled' : 'disabled'}`); },
    getLogs: () => logs,
    runTask
};
